### ISSUE TITLE
database and cluster access via matlab

### ISSUE THREAD

**Issue by cjayb** [meeg-cfin/sandbox#1]
[Martin D.]: I'd be happy to contribute with the following topics and document them on the wiki :
1. Querying the Storm database when working in Matlab.
2. Submitting jobs to Hyades cluster from Matlab
3. Writing "clusterised" recipes for Matlab-based toolboxes

**Comment by martinjdietz** [comment]
1. is done. Please test and add requests to "issues".

**Comment by sarathykousik** [comment]
@martinjdietz has added the function. this issue must be closed. @cjayb
